version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: frontend_container
    ports:
      - 80:80
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
